### ISSUE TITLE
Impossible to plot a route to Terra Nullius

### ISSUE THREAD

**Issue by krzysztof-sikorski** [plscks/testHYPERMAP#87]
On the "Wyrm's Lair" map there are two tiles that are displayed as being adjacent, while in fact they are not actually adjacent in game and it is impossible to directly step between them:
- "[8,10] Terra Nullius - The River Vivax (inside a river)" (displayed in 11,12 position
- "[9,10] Terra Nullius - Andrea Vendetta (inside a colonial ship deck)", displayed in 12,12 position

This tile placement confuses pathfinding algorithm and makes it impossible to plot a path, any path, into Terra Nullius plane, because the alogirthm is always suggesting to step from the ship wreck into the river - an action that is actually imposible in game.

I am not sure if this is a bug or a hidden feature, but I decided to report it here just in case :wink:

**Comment by plscks** [comment]
Thank you so much for starting this issue, one can't fix things if they don't know they are broken right? 

This is actually by design, not mine, but the games. The only way to see the river tile is if you are inside the Andrea Vendetta and have an ability or status effect that allows you to traverse water for 0.5ap per tile (I think?). Swim, Waterbreathing (via potion or spell), lesser flight like Feet of the Wind, Ghostwalk, Wisp Form, Way of the Lightning, Bat form, Wolf form, just to name a few. This effectively bars certain angels, demons (as they have wings and cannot activate them inside), and Lich from entering without the waterbreathing status effect.

**Comment by krzysztof-sikorski** [comment]
This is an interesting hidden feature of the game, I always assumed that travel abilities only reduced movement costs and did not unlock new movement directions.

This also means that the issue is not technically a bug, although it would be a nice little quality-of-life feature if the map had a switch to toggle on/off that particular path. Or maybe the existing "Water Cost" switch could be upgraded to have this side effect?

Anyway thank you very much for explaining the game feature :smile:

**Comment by plscks** [comment]
> This also means that the issue is not technically a bug, although it would be a nice little quality-of-life feature if the map had a switch to toggle on/off that particular path. Or maybe the existing "Water Cost" switch could be upgraded to have this side effect?

Yeah I can certainly look into making this happen.

**Comment by krzysztof-sikorski** [comment]
Because Breath 5 has been announced to be released in next few months, I think this issue can be closed - the new Breath will introduce a completely new map with its own set of secrets and quirks, so any Hypermap changes will be completely unrelated to this particular topic.
